openapi: 3.0.0
info:
  title: 'My First API'
  version: '0.1'
paths:
  /banner:
    get:
      operationId: 'App\Http\Controllers\BannerController::__invoke'
      responses:
        '200':
          description: 'Display a listing of projects.'
  /cart:
    get:
      operationId: 'App\Http\Controllers\CartController::__construct'
      responses:
        '200':
          description: 'Display a listing of projects.'
  /category:
    get:
      operationId: 'App\Http\Controllers\CategoryController::__construct'
      responses:
        '200':
          description: 'Display a listing of projects.'

